domain: []
external_id_method: row_get_id
external_id_nomenclature: product_template_%s
fields:
  accessory_product_ids:
    from:
      name: accessory_product_ids
      relation: product.product
      type: many2many
    map_method: magic_map
    to:
      name: accessory_product_ids
      relation: product.product
      type: many2many
  alternative_product_ids:
    from:
      name: alternative_product_ids
      relation: product.template
      type: many2many
    map_method: magic_map
    to:
      name: alternative_product_ids
      relation: product.template
      type: many2many
  public_categ_ids:
    from:
      name: public_categ_ids
      relation: product.public.category
      type: many2many
    map_method: magic_map
    to:
      name: public_categ_ids
      relation: product.public.category
      type: many2many
  website_description:
    from:
      name: website_description
      type: html
    map_method: magic_map
    to:
      name: website_description
      type: html
  website_message_ids:
    from:
      name: website_message_ids
      relation: mail.message
      relation_field: res_id
      type: one2many
    map_method: magic_map
    to:
      name: website_message_ids
      relation: mail.message
      relation_field: res_id
      type: one2many
  website_meta_description:
    from:
      name: website_meta_description
      type: text
    map_method: magic_map
    to:
      name: website_meta_description
      type: text
  website_meta_keywords:
    from:
      name: website_meta_keywords
      type: char
    map_method: magic_map
    to:
      name: website_meta_keywords
      type: char
  website_meta_title:
    from:
      name: website_meta_title
      type: char
    map_method: magic_map
    to:
      name: website_meta_title
      type: char
  website_published:
    from:
      name: website_published
      type: boolean
    map_method: magic_map
    to:
      name: website_published
      type: boolean
  website_sequence:
    from:
      name: website_sequence
      type: integer
    map_method: magic_map
    to:
      name: website_sequence
      type: integer
  website_size_x:
    from:
      name: website_size_x
      type: integer
    map_method: magic_map
    to:
      name: website_size_x
      type: integer
  website_size_y:
    from:
      name: website_size_y
      type: integer
    map_method: magic_map
    to:
      name: website_size_y
      type: integer
  website_style_ids:
    from:
      name: website_style_ids
      relation: product.style
      type: many2many
    map_method: magic_map
    to:
      name: website_style_ids
      relation: product.style
      type: many2many
model_from: product.template
model_to: product.template
no_match_fields:
  website_url:
    from:
      name: website_url
      type: char
