domain: []
external_id_method: row_get_id
external_id_nomenclature: product_uom_categ_%s
fields:
  name:
    from:
      name: name
      type: char
    map_method: magic_map
    to:
      name: name
      type: char
model_from: product.uom.categ
model_to: uom.category
