domain: []
external_id_method: row_get_id
external_id_nomenclature: product_template_%s
fields:
  purchase_ok:
    from:
      name: purchase_ok
      type: boolean
    map_method: magic_map
    to:
      name: purchase_ok
      type: boolean
model_from: product.template
model_to: product.template
