domain: []
external_id_method: row_get_id
external_id_nomenclature: product_pricelist_%s
fields:
  sequence:
    from:
      name: sequence
      type: integer
    map_method: magic_map
    to:
      name: sequence
      type: integer
model_from: product.pricelist
model_to: product.pricelist
